name: Build & Deploy
on:
  fork:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST_V}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY_V}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME_V}} # User of the server you want to ssh into
          passphrase: ${{ secrets.SERVER_PASSPHRASE_V}}
     
          script: |
            # Якщо репозиторій уже є, оновлюємо його. Якщо ні — клонуємо
            if [ -d "laba223" ]; then
              cd laba223
              git pull origin main
            else
              git clone https://github.com/VADUMr/laba223.git
              cd laba223
            fi
            echo 'Deployment successful to digital ocean d1' 
